blogs/urls.py
from django.urls import path

from blogs.views import BlogListView, BlogDetailView

app_name = 'blogs'

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('detail/<int:pk>/', BlogDetailView.as_view(), name='detail'),
]

conf/urls.py
from aiogram.types import contact
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('products/', include('products.urls', namespace='products')),
    path('shop/', include('shop.urls', namespace='shops')),
    path('orders/', include('orders.urls', namespace='orders')),
)


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.db import models


class AuthorModel(models.Model):
    name = models.CharField(max_length=128, verbose_name=_('name'))
    image = models.ImageField(upload_to='blogs-author')
    about = models.TextField(verbose_name=_('about'), blank=True)
    position = models.CharField(max_length=128, verbose_name=_('position'))
    profession = models.CharField(max_length=128, verbose_name=_('profession'))

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Author')
        verbose_name_plural = _('Authors')


class BlogCategoryModel(models.Model):
    name = models.CharField(max_length=128, verbose_name=_('category name'))

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')


class BlogTagModel(models.Model):
    name = models.CharField(max_length=128, verbose_name=_('blog tag'))

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Tag')
        verbose_name_plural = _('Tags')


class BlogModel(models.Model):
    title = models.CharField(max_length=255, verbose_name=_('title blog'), db_index=True)
    image = models.ImageField(upload_to='blog-images')
    short_info = models.TextField(null=True, verbose_name=_('short_info'))
    content = models.TextField(verbose_name=_('content'))
    categories = models.ManyToManyField(BlogCategoryModel, related_name='blogs')
    tags = models.ManyToManyField(BlogTagModel, related_name='tags')
    authors = models.ForeignKey(AuthorModel, on_delete=models.CASCADE, related_name='blogs')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('blog')
        verbose_name_plural = _('blogs')

blogs/views.py
# django own imports

from django.shortcuts import render
from django.views.generic import TemplateView, ListView


#blogs own imports
from blogs.models import BlogModel, BlogCategoryModel, BlogTagModel


class BlogListView(ListView):
    template_name = 'blogs/blog-list.html'
    context_object_name = 'blogs'
    model = BlogModel
    paginate_by = 2

    def get_queryset(self):
        queryset = BlogModel.objects.all().order_by('-pk')
        tags = self.request.GET.get('tags')
        categories = self.request.GET.get('categories')

        if tags:
            queryset = queryset.filter(tags=tags)
        if categories:
            queryset = queryset.filter(categories=categories)

        return queryset

    def get_context_data(self, *, object_list=None,  **kwargs):
        context = {
            "blogs": BlogModel.objects.all().order_by('-created_at'),
            "categories": BlogCategoryModel.objects.all(),
            "tags": BlogTagModel.objects.all(),
            "famous_blogs": BlogModel.objects.all().order_by('-created_at')[::-2]
        }
        return context


class BlogDetailView(TemplateView):
    template_name = 'blogs/blog-detail.html'
    context_object_name = 'blog'
    model = BlogModel

    def get_context_data(self, *, object_list=None, **kwargs):
        context = {
            "categories": BlogCategoryModel.objects.all(),
            "blog": BlogModel.objects.get(pk=self.kwargs['pk']),
            "tags": BlogTagModel.objects.all(),
            "famous_blogs": BlogModel.objects.all().order_by('-created_at')[:2],
            "related_blogs": BlogModel.objects.filter(categories__in=self.object.categories.all()).order_by(
                '-created_at')[:3],
        }
        return context

templates/blogs/blog-list.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">

<!-- blog-list31:56-->
<head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>Blog List || limupa - Digital Products Store eCommerce Bootstrap 4 Template</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Favicon -->
        <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.png'%}">
        <!-- Material Design Iconic Font-V2.2.0 -->
        <link rel="stylesheet" href="{% static 'css/material-design-iconic-font.min.css'%}">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css'%}">
        <!-- Font Awesome Stars-->
        <link rel="stylesheet" href="{% static 'css/fontawesome-stars.css'%}">
        <!-- Meanmenu CSS -->
        <link rel="stylesheet" href="{% static 'css/meanmenu.css'%}">
        <!-- owl carousel CSS -->
        <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css'%}">
        <!-- Slick Carousel CSS -->
        <link rel="stylesheet" href="{% static 'css/slick.css'%}">
        <!-- Animate CSS -->
        <link rel="stylesheet" href="{% static 'css/animate.css'%}">
        <!-- Jquery-ui CSS -->
        <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css'%}">
        <!-- Venobox CSS -->
        <link rel="stylesheet" href="{% static 'css/venobox.css'%}">
        <!-- Nice Select CSS -->
        <link rel="stylesheet" href="{% static 'css/nice-select.css'%}">
        <!-- Magnific Popup CSS -->
        <link rel="stylesheet" href="{% static 'css/magnific-popup.css'%}">
        <!-- Bootstrap V4.1.3 Fremwork CSS -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
        <!-- Helper CSS -->
        <link rel="stylesheet" href="{% static 'css/helper.css'%}">
        <!-- Main Style CSS -->
        <link rel="stylesheet" href="{% static 'css/style.css'%}">
        <!-- Responsive CSS -->
        <link rel="stylesheet" href="{% static 'css/responsive.css'%}">
        <!-- Modernizr js -->
        <script src="{% static 'js/vendor/modernizr-2.8.3.min.js'%}"></script>
    </head>
    <body>
    <!--[if lt IE 8]>
		<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
	<![endif]-->
        <!-- Begin Body Wrapper -->
        <div class="body-wrapper">
            <!-- Begin Header Area -->
            {% include 'layouts/header-base.html' %}
            <!-- Header Area End Here -->
            <!-- Begin Li's Breadcrumb Area -->
            <div class="breadcrumb-area">
                <div class="container">
                    <div class="breadcrumb-content">
                        <ul>
                            <li><a href="index.html">Home</a></li>
                            <li class="active">Blog List</li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- Li's Breadcrumb Area End Here -->
            <!-- Begin Li's Main Blog Page Area -->
            <div class="li-main-blog-page pt-60 pb-55">
                <div class="container">
                    <div class="row">
                        <!-- Begin Li's Main Content Area -->
                        <div class="col-lg-12">
                            <div class="row li-main-content">
                                {% for blog in blogs %}
                                <div class="col-lg-12">
                                    <div class="li-blog-single-item pb-30">
                                        <div class="row">
                                            <div class="col-lg-6">
                                                <div class="li-blog-banner">
                                                    <a href="{% url 'blogs:detail' %}"><img class="img-full" src="{{ blog.image.url }}" alt=""></a>
                                                </div>
                                            </div>
                                            <div class="col-lg-6">
                                                <div class="li-blog-content">
                                                    <div class="li-blog-details">
                                                        <h3 class="li-blog-heading pt-xs-25 pt-sm-25"><a href="{% url 'blogs:detail' %}">{{ blog.title }}</a></h3>
                                                        <div class="li-blog-meta">
                                                            <a class="author" href="#"><i class="fa fa-user"></i>{{ blog.authors.name }}</a>
                                                            <a class="comment" href="#"><i class="fa fa-comment-o"></i>{{ blog.short_info }}</a>
                                                            <a class="post-time" href="#"><i class="fa fa-calendar"></i>{{ blog.created_at }}</a>
                                                        </div>
                                                        <p>{{ blog.short_infoclearclear }}</p>
                                                        <a class="read-more" href="{% url 'blogs:detail' %}">Read More...</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                                <!-- Begin Li's Pagination Area -->
                                <div class="col-lg-12">
                                    <div class="li-paginatoin-area text-center pt-25">
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <ul class="li-pagination-box">
                                                    <li><a class="Previous" href="#">Previous</a></li>
                                                    <li class="active"><a href="#">1</a></li>
                                                    <li><a href="#">2</a></li>
                                                    <li><a href="#">3</a></li>
                                                    <li><a class="Next" href="#">Next</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- Li's Pagination End Here Area -->
                            </div>
                        </div>
                        <!-- Li's Main Content Area End Here -->
                    </div>
                </div>
            </div>
            <!-- Li's Main Blog Page Area End Here -->
            <!-- Begin Footer Area -->
            {% include 'layouts/footer.html' %}
            <!-- Footer Area End Here -->
        </div>
        <!-- Body Wrapper End Here -->
        <!-- jQuery-V1.12.4 -->
        <script src="{% static 'js/vendor/jquery-1.12.4.min.js'%}"></script>
        <!-- Popper js -->
        <script src="{% static 'js/vendor/popper.min.js'%}"></script>
        <!-- Bootstrap V4.1.3 Fremwork js -->
        <script src="{% static 'js/bootstrap.min.js'%}"></script>
        <!-- Ajax Mail js -->
        <script src="{% static 'js/ajax-mail.js'%}"></script>
        <!-- Meanmenu js -->
        <script src="{% static 'js/jquery.meanmenu.min.js'%}"></script>
        <!-- Wow.min js -->
        <script src="{% static 'js/wow.min.js'%}"></script>
        <!-- Slick Carousel js -->
        <script src="{% static 'js/slick.min.js'%}"></script>
        <!-- Owl Carousel-2 js -->
        <script src="{% static 'js/owl.carousel.min.js'%}"></script>
        <!-- Magnific popup js -->
        <script src="{% static 'js/jquery.magnific-popup.min.js'%}"></script>
        <!-- Isotope js -->
        <script src="{% static 'js/isotope.pkgd.min.js'%}"></script>
        <!-- Imagesloaded js -->
        <script src="{% static 'js/imagesloaded.pkgd.min.js'%}"></script>
        <!-- Mixitup js -->
        <script src="{% static 'js/jquery.mixitup.min.js'%}"></script>
        <!-- Countdown -->
        <script src="{% static 'js/jquery.countdown.min.js'%}"></script>
        <!-- Counterup -->
        <script src="{% static 'js/jquery.counterup.min.js'%}"></script>
        <!-- Waypoints -->
        <script src="{% static 'js/waypoints.min.js'%}"></script>
        <!-- Barrating -->
        <script src="{% static 'js/jquery.barrating.min.js'%}"></script>
        <!-- Jquery-ui -->
        <script src="{% static 'js/jquery-ui.min.js'%}"></script>
        <!-- Venobox -->
        <script src="{% static 'js/venobox.min.js'%}"></script>
        <!-- Nice Select js -->
        <script src="{% static 'js/jquery.nice-select.min.js'%}"></script>
        <!-- ScrollUp js -->
        <script src="{% static 'js/scrollUp.min.js'%}"></script>
        <!-- Main/Activator js -->
        <script src="{% static 'js/main.js'%}"></script>
    </body>

<!-- blog-list31:56-->
</html>